apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo
data:
  PORT: "8080"
  DB_NAME: much_todo_db
  JWT_EXPIRATION_HOURS: "72"
  LOG_LEVEL: INFO
  LOG_FORMAT: json
  ENABLE_CACHE: "false"
